name: CI

on: [push]

env:
  target: thumbv7em-none-eabi
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        rust_toolchain:
          - nightly
          - stable
          - beta
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3

      - name: Setup | Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust_toolchain }}
          targets: ${{ env.target }}
          components: rustfmt, rust-src

      - name: Build | Compile, all
        run: cargo build --target ${{ env.target }} --verbose
